# -*- coding: utf-8 -*-
"""States Product Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVDmkTK9yTLdKAaybyNCFrkthZq67Mfb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data from Excel
file_path = '/content/Online Sale.xlsx'
df = pd.read_excel(file_path)

# Data Analysis
df['Total Sales'] = df['Price of Product'] * df['Number of Quantity']
total_sales_by_state = df.groupby('State')['Total Sales'].sum().reset_index()
total_quantity_by_product = df.groupby('Product Sold')['Number of Quantity'].sum().reset_index()

# Data Visualization

# Bar Plot of Total Sales by State
plt.figure(figsize=(10, 6))
sns.barplot(x='State', y='Total Sales', data=total_sales_by_state, palette='viridis')
plt.title('Total Sales by State')
plt.xlabel('State')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

# Pie Chart of Total Quantity Sold by Product
plt.figure(figsize=(8, 8))
plt.pie(total_quantity_by_product['Number of Quantity'], labels=total_quantity_by_product['Product Sold'],
        autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Total Quantity Sold by Product')
plt.axis('equal')
plt.show()

# Scatter Plot of Price vs Quantity
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Price of Product', y='Number of Quantity', data=df, hue='Product Sold', style='State', palette='deep')
plt.title('Price vs Quantity Sold')
plt.xlabel('Price of Product')
plt.ylabel('Number of Quantity')
plt.legend(bbox_to_anchor=(1.05, 1), loc=2)
plt.show()

